apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-n6jp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-n6jp
    app.kubernetes.io/part-of: tkrw-pr714-0075-0059-app
  name: devfile-sample-n6jp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-n6jp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-n6jp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0059-tenant/tkrw-pr714-0075-0059-app/devfile-sample-n6jp@sha256:6e10e9d854a7c4a4d202251dd389346976389b3509e6cb0f244a8e9ce4033678
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
